//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DwSi.service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.communication.service.dareway.com/", ConfigurationName="service.IMsh5Service")]
    public interface IMsh5Service {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        string login(string arg0, string arg1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="loginResult1")]
        string loginByYybm(string arg0, string arg1, string arg2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="resultContent")]
        string invoke(string arg0, string arg1, string arg2, string arg3, string arg4);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="resultContent")]
        string invokeSi(string arg0, string arg1, string arg2, string arg3, string arg4);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="resultContent")]
        string invokeCotton(string arg0, string arg1, string arg2, string arg3, string arg4, string arg5);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="resultContent")]
        string dipInvoke(string arg0, string arg1, string arg2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="resultContent")]
        string pipInvoke(string arg0, string arg1, string arg2, string arg3, string arg4, string arg5);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="resultContent")]
        string invokeCheckZcm(string arg0, string arg1, string arg2, string arg3, string arg4, string arg5);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMsh5ServiceChannel : DwSi.service.IMsh5Service, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Msh5ServiceClient : System.ServiceModel.ClientBase<DwSi.service.IMsh5Service>, DwSi.service.IMsh5Service {
        
        public Msh5ServiceClient() {
        }
        
        public Msh5ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Msh5ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Msh5ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Msh5ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string login(string arg0, string arg1) {
            return base.Channel.login(arg0, arg1);
        }
        
        public string loginByYybm(string arg0, string arg1, string arg2) {
            return base.Channel.loginByYybm(arg0, arg1, arg2);
        }
        
        public string invoke(string arg0, string arg1, string arg2, string arg3, string arg4) {
            return base.Channel.invoke(arg0, arg1, arg2, arg3, arg4);
        }
        
        public string invokeSi(string arg0, string arg1, string arg2, string arg3, string arg4) {
            return base.Channel.invokeSi(arg0, arg1, arg2, arg3, arg4);
        }
        
        public string invokeCotton(string arg0, string arg1, string arg2, string arg3, string arg4, string arg5) {
            return base.Channel.invokeCotton(arg0, arg1, arg2, arg3, arg4, arg5);
        }
        
        public string dipInvoke(string arg0, string arg1, string arg2) {
            return base.Channel.dipInvoke(arg0, arg1, arg2);
        }
        
        public string pipInvoke(string arg0, string arg1, string arg2, string arg3, string arg4, string arg5) {
            return base.Channel.pipInvoke(arg0, arg1, arg2, arg3, arg4, arg5);
        }
        
        public string invokeCheckZcm(string arg0, string arg1, string arg2, string arg3, string arg4, string arg5) {
            return base.Channel.invokeCheckZcm(arg0, arg1, arg2, arg3, arg4, arg5);
        }
    }
}
